# Generated by Django 4.2 on 2023-04-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('quantity_used', models.IntegerField()),
                ('remaining_stock', models.IntegerField()),
            ],
        ),
    ]
