# Generated by Django 4.2 on 2023-04-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='remaining_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
